//! Migrating a whole style to modern expressions — the counterpart of
//! maplibre-style-spec's `migrate`.
//!
//! Real-world v8 styles (the MapLibre demo tiles included) still carry three
//! pre-expression forms: legacy *function objects* (`{ "stops": … }`) in
//! layout/paint properties, `{token}` strings in `text-field` / `icon-image`,
//! and legacy filters with bare property names. MapLibre converts all of them
//! before evaluating, using the style-spec *reference* to know each property's
//! type, whether it interpolates, whether it accepts tokens, and so on.
//!
//! [`migrate`] does the same here: it walks every layer of a v8 style and
//! rewrites those forms to expressions, so the result contains only what
//! [`parse`](crate::parse) / [`parse_filter`](crate::filter::parse_filter)
//! understand natively. The reference it consults is a pruned snapshot of the
//! upstream `v8.json`, embedded in the crate (see `src/reference/`), so no
//! external input is needed; [`migrate_with`] takes a custom reference instead.
//!
//! [`parse`](crate::parse), like MapLibre's `createExpression`, reads only
//! expressions; migrate a style (or use [`parse_property`](crate::parse_property)
//! for one value) before handing legacy forms to it. The property's spec is
//! what tells an interpolated `line-width` from a stepped `text-transform` and
//! whether a string carries tokens, so guessing without it would not match
//! MapLibre.
//!
//! Like upstream, migration only understands `version: 8` styles; the ancient
//! v7 → v8 rewrite is not ported.

use std::fmt;
use std::sync::OnceLock;

use serde_json::{Map, Value as Json};

use crate::convert::{convert_function, convert_token_string};
use crate::filter::{convert_legacy_filter, FilterError};

/// The embedded, pruned style-spec reference: property name → the spec fields
/// the legacy conversion needs. Generated by `scripts/refresh_reference.sh`.
const REFERENCE_JSON: &str = include_str!("reference/v8.json");

/// The embedded style-spec reference used by [`migrate`]: a JSON object keyed
/// by layout/paint property name (`"line-width"`, `"text-field"`, …), each
/// value holding the property's `type`, `default`, `expression`, `tokens`,
/// `values`, `value` and `length` as in the upstream `v8.json`.
pub fn reference() -> &'static Json {
    static REFERENCE: OnceLock<Json> = OnceLock::new();
    REFERENCE.get_or_init(|| {
        serde_json::from_str(REFERENCE_JSON).expect("embedded reference is valid JSON")
    })
}

/// The spec entry for a layout/paint property, looked up by name alone across
/// all layer types (as upstream does), or `None` for an unknown property.
pub fn property_spec(name: &str) -> Option<&'static Json> {
    reference().get(name)
}

/// Why a style could not be migrated.
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub enum MigrateError {
    /// The style's `version` was not `8` (or was missing). Carries the value
    /// found.
    UnsupportedVersion(Json),
    /// The style is not an object, or its `layers` is not an array of objects.
    Malformed(String),
    /// A layer's legacy filter could not be converted.
    Filter { layer: String, source: FilterError },
}

impl fmt::Display for MigrateError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            MigrateError::UnsupportedVersion(v) => {
                let v = match v {
                    Json::Null => "undefined".to_string(),
                    other => other.to_string(),
                };
                write!(f, "Cannot migrate from {v}")
            }
            MigrateError::Malformed(what) => write!(f, "malformed style: {what}"),
            MigrateError::Filter { layer, source } => {
                write!(f, "layer {layer:?}: {source}")
            }
        }
    }
}

impl std::error::Error for MigrateError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            MigrateError::Filter { source, .. } => Some(source),
            _ => None,
        }
    }
}

/// Migrate a v8 style so that every layer filter and layout/paint value is a
/// modern expression (or a plain literal), using the embedded [`reference()`].
///
/// Per layer this converts a legacy filter, converts each function object in
/// `layout` / `paint` with the property's spec, expands `{token}` strings in
/// token-accepting properties, and normalises non-standard `hsl()` colors in
/// color-typed properties (see [`migrate_colors`]). Everything else — sources,
/// metadata, values that are already expressions, `*-transition` entries,
/// properties unknown to the reference — is left untouched. The input is not
/// modified; the migrated style is returned.
pub fn migrate(style: &Json) -> Result<Json, MigrateError> {
    migrate_with(style, reference())
}

/// [`migrate`] with a custom reference: a JSON object keyed by property name
/// with the same shape as [`reference()`] (a full upstream `v8.json` section
/// flattened, or a fork of it).
pub fn migrate_with(style: &Json, reference: &Json) -> Result<Json, MigrateError> {
    let mut style = style.clone();
    let obj = style
        .as_object_mut()
        .ok_or_else(|| MigrateError::Malformed("style is not an object".into()))?;

    let version = obj.get("version").cloned().unwrap_or(Json::Null);
    if version.as_f64() != Some(8.0) {
        return Err(MigrateError::UnsupportedVersion(version));
    }

    let Some(layers) = obj.get_mut("layers") else {
        return Ok(style);
    };
    let layers = layers
        .as_array_mut()
        .ok_or_else(|| MigrateError::Malformed("`layers` is not an array".into()))?;
    for layer in layers.iter_mut() {
        let layer = layer
            .as_object_mut()
            .ok_or_else(|| MigrateError::Malformed("a layer is not an object".into()))?;
        migrate_layer(layer, reference)?;
    }
    Ok(style)
}

fn migrate_layer(layer: &mut Map<String, Json>, reference: &Json) -> Result<(), MigrateError> {
    // Upstream: `if (layer.filter) layer.filter = convertFilter(layer.filter)`.
    if let Some(filter) = layer.get("filter").filter(|f| js_truthy(f)) {
        let converted = convert_legacy_filter(filter).map_err(|source| MigrateError::Filter {
            layer: layer
                .get("id")
                .and_then(Json::as_str)
                .unwrap_or_default()
                .to_string(),
            source,
        })?;
        layer.insert("filter".into(), converted);
    }
    for section in ["paint", "layout"] {
        if let Some(Json::Object(props)) = layer.get_mut(section) {
            for (name, value) in props.iter_mut() {
                let migrated = migrate_property_with(name, value, reference);
                *value = migrated;
            }
        }
    }
    Ok(())
}

/// Migrate one layout/paint property value using the embedded [`reference()`]:
/// a function object becomes an expression, a `{token}` string in a
/// token-accepting property becomes an expression, a color-typed value has
/// its `hsl()` colors normalised, and anything else is returned unchanged.
///
/// This is the per-property building block of [`migrate`], for when you hold
/// a single style value rather than a whole style.
pub fn migrate_property(name: &str, value: &Json) -> Json {
    migrate_property_with(name, value, reference())
}

/// [`migrate_property`] with a custom reference (see [`migrate_with`]).
pub fn migrate_property_with(name: &str, value: &Json, reference: &Json) -> Json {
    let Some(spec) = reference.get(name) else {
        return value.clone();
    };
    let mut value = value.clone();
    if !crate::is_expression(&value) && !name.ends_with("-transition") {
        match &value {
            Json::Object(_) => value = convert_function(&value, spec),
            Json::String(s) if spec.get("tokens") == Some(&Json::Bool(true)) => {
                value = convert_token_string(s)
            }
            _ => {}
        }
    }
    if spec.get("type").and_then(Json::as_str) == Some("color") {
        value = migrate_colors(&value);
    }
    value
}

/// Rewrite `hsl()` / `hsla()` color strings that the old `csscolorparser`
/// accepted but the CSS Color specification does not — fractional saturation
/// and lightness, `hsl(900, 0.15, 90%)` — to the compliant `hsl(900,15%,90%)`.
/// Applied to every string inside `value` (so expressions are covered too);
/// standard colors and non-color strings are returned unchanged.
pub fn migrate_colors(value: &Json) -> Json {
    match value {
        Json::String(s) => Json::String(migrate_hsl(s).unwrap_or_else(|| s.clone())),
        Json::Array(items) => Json::Array(items.iter().map(migrate_colors).collect()),
        Json::Object(map) => Json::Object(
            map.iter()
                .map(|(k, v)| (k.clone(), migrate_colors(v)))
                .collect(),
        ),
        other => other.clone(),
    }
}

/// Port of upstream `migrateHslColors`, which runs the regex
/// `"hsla?\((.+?)\)"` over the *serialised* value and then splits the
/// arguments with `^(.+?)\s*,\s*(.+?)\s*,\s*(.+?)(?:\s*,\s*(.+))?$`. Returns
/// `None` when the string is left as is.
fn migrate_hsl(s: &str) -> Option<String> {
    let lower = s.to_ascii_lowercase();
    let open = if lower.starts_with("hsla(") {
        5
    } else if lower.starts_with("hsl(") {
        4
    } else {
        return None;
    };
    // `.` does not match a newline, and the lazy `(.+?)\)"` must reach the
    // closing quote, i.e. the string's final character.
    if !s.ends_with(')') || s.contains('\n') {
        return None;
    }
    let args = &s[open..s.len() - 1];

    // `(.+?)\s*,\s*` three times: split on the first commas, trimming the
    // whitespace around each comma; the head of the first group is not trimmed.
    let (h, rest) = split_arg(args)?;
    let (sat, rest) = split_arg(rest)?;
    // `(.+?)(?:\s*,\s*(.+))?$`: a fourth argument only if non-empty after the
    // comma; otherwise the third group runs to the end.
    let (light, alpha) = match split_arg(rest) {
        Some((l, a)) if !a.is_empty() => (l, Some(a)),
        _ => (rest, None),
    };
    if h.is_empty() || sat.is_empty() || light.is_empty() {
        return None;
    }

    let percent = |v: &str| -> String {
        if v.ends_with('%') {
            v.to_string()
        } else {
            format!("{}%", js_number_to_string(js_parse_float(v) * 100.0))
        }
    };
    let mut parts = vec![h.to_string(), percent(sat), percent(light)];
    if let Some(a) = alpha {
        parts.push(a.to_string());
    }
    Some(format!(
        "hsl{}({})",
        if alpha.is_some() { "a" } else { "" },
        parts.join(",")
    ))
}

/// `(.+?)\s*,\s*` — the text before the first comma (trailing whitespace
/// trimmed, must be non-empty) and the text after it (leading whitespace
/// trimmed).
fn split_arg(s: &str) -> Option<(&str, &str)> {
    let comma = s.find(',')?;
    let head = s[..comma].trim_end();
    if head.is_empty() {
        return None;
    }
    Some((head, s[comma + 1..].trim_start()))
}

/// JavaScript's `parseFloat`: skip leading whitespace, parse the longest
/// numeric prefix, `NaN` if there is none.
fn js_parse_float(s: &str) -> f64 {
    let s = s.trim_start();
    let b = s.as_bytes();
    let mut i = 0;
    if i < b.len() && (b[i] == b'+' || b[i] == b'-') {
        i += 1;
    }
    let int_start = i;
    while i < b.len() && b[i].is_ascii_digit() {
        i += 1;
    }
    let mut digits = i - int_start;
    if i < b.len() && b[i] == b'.' {
        let frac_start = i + 1;
        let mut j = frac_start;
        while j < b.len() && b[j].is_ascii_digit() {
            j += 1;
        }
        digits += j - frac_start;
        if j > frac_start || digits > 0 {
            i = j;
        }
    }
    if digits == 0 {
        return f64::NAN;
    }
    if i < b.len() && (b[i] == b'e' || b[i] == b'E') {
        let mut j = i + 1;
        if j < b.len() && (b[j] == b'+' || b[j] == b'-') {
            j += 1;
        }
        let exp_start = j;
        while j < b.len() && b[j].is_ascii_digit() {
            j += 1;
        }
        if j > exp_start {
            i = j;
        }
    }
    s[..i].parse().unwrap_or(f64::NAN)
}

/// JavaScript's `Number#toString` for the values `parseFloat(v) * 100` can
/// produce here: shortest round-trip digits, `NaN`, `Infinity`.
fn js_number_to_string(n: f64) -> String {
    if n.is_nan() {
        "NaN".into()
    } else if n.is_infinite() {
        if n > 0.0 { "Infinity" } else { "-Infinity" }.into()
    } else {
        n.to_string()
    }
}

/// JavaScript truthiness of a JSON value.
fn js_truthy(v: &Json) -> bool {
    match v {
        Json::Null => false,
        Json::Bool(b) => *b,
        Json::Number(n) => n.as_f64().is_some_and(|f| f != 0.0),
        Json::String(s) => !s.is_empty(),
        Json::Array(_) | Json::Object(_) => true,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hsl_examples_from_upstream_doc() {
        assert_eq!(
            migrate_hsl("hsl(900, 0.15, 90%)").as_deref(),
            Some("hsl(900,15%,90%)")
        );
        assert_eq!(
            migrate_hsl("hsla(900, .15, .9)").as_deref(),
            Some("hsl(900,15%,90%)")
        );
        assert_eq!(
            migrate_hsl("hsl(900, 15%, 90%)").as_deref(),
            Some("hsl(900,15%,90%)")
        );
        assert_eq!(
            migrate_hsl("hsla(900, 0.15, 90%, 0.5)").as_deref(),
            Some("hsla(900,15%,90%,0.5)")
        );
        assert_eq!(migrate_hsl("rgb(1, 2, 3)"), None);
        assert_eq!(migrate_hsl("hsl(1)"), None);
    }

    #[test]
    fn parse_float_matches_js() {
        assert_eq!(js_parse_float(".9"), 0.9);
        assert_eq!(js_parse_float(" 0.15abc"), 0.15);
        assert_eq!(js_parse_float("1e2"), 100.0);
        assert!(js_parse_float("abc").is_nan());
    }
}
